/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedWorkspacesRouteImport } from './routes/_authenticated.workspaces'
import { Route as AuthenticatedTerminalRouteImport } from './routes/_authenticated.terminal'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated.tasks'
import { Route as AuthenticatedStorageRouteImport } from './routes/_authenticated.storage'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedServersRouteImport } from './routes/_authenticated.servers'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated.integrations'
import { Route as AuthenticatedFilesRouteImport } from './routes/_authenticated.files'
import { Route as AuthenticatedDatabasesRouteImport } from './routes/_authenticated.databases'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedControlPlaneRouteImport } from './routes/_authenticated.control-plane'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated.chat'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated.audit-log'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated.approvals'
import { Route as AuthenticatedTasksIdRouteImport } from './routes/_authenticated.tasks.$id'
import { Route as AuthenticatedFilesSplatRouteImport } from './routes/_authenticated.files.$'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspacesRoute = AuthenticatedWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTerminalRoute = AuthenticatedTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStorageRoute = AuthenticatedStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServersRoute = AuthenticatedServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFilesRoute = AuthenticatedFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDatabasesRoute = AuthenticatedDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedControlPlaneRoute =
  AuthenticatedControlPlaneRouteImport.update({
    id: '/control-plane',
    path: '/control-plane',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksIdRoute = AuthenticatedTasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTasksRoute,
} as any)
const AuthenticatedFilesSplatRoute = AuthenticatedFilesSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthenticatedFilesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/chat': typeof AuthenticatedChatRoute
  '/control-plane': typeof AuthenticatedControlPlaneRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/databases': typeof AuthenticatedDatabasesRoute
  '/files': typeof AuthenticatedFilesRouteWithChildren
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/servers': typeof AuthenticatedServersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/storage': typeof AuthenticatedStorageRoute
  '/tasks': typeof AuthenticatedTasksRouteWithChildren
  '/terminal': typeof AuthenticatedTerminalRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/api/chat': typeof ApiChatRoute
  '/files/$': typeof AuthenticatedFilesSplatRoute
  '/tasks/$id': typeof AuthenticatedTasksIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/chat': typeof AuthenticatedChatRoute
  '/control-plane': typeof AuthenticatedControlPlaneRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/databases': typeof AuthenticatedDatabasesRoute
  '/files': typeof AuthenticatedFilesRouteWithChildren
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/servers': typeof AuthenticatedServersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/storage': typeof AuthenticatedStorageRoute
  '/tasks': typeof AuthenticatedTasksRouteWithChildren
  '/terminal': typeof AuthenticatedTerminalRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/api/chat': typeof ApiChatRoute
  '/': typeof AuthenticatedIndexRoute
  '/files/$': typeof AuthenticatedFilesSplatRoute
  '/tasks/$id': typeof AuthenticatedTasksIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/control-plane': typeof AuthenticatedControlPlaneRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/databases': typeof AuthenticatedDatabasesRoute
  '/_authenticated/files': typeof AuthenticatedFilesRouteWithChildren
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/servers': typeof AuthenticatedServersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/storage': typeof AuthenticatedStorageRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRouteWithChildren
  '/_authenticated/terminal': typeof AuthenticatedTerminalRoute
  '/_authenticated/workspaces': typeof AuthenticatedWorkspacesRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/files/$': typeof AuthenticatedFilesSplatRoute
  '/_authenticated/tasks/$id': typeof AuthenticatedTasksIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/approvals'
    | '/audit-log'
    | '/chat'
    | '/control-plane'
    | '/dashboard'
    | '/databases'
    | '/files'
    | '/integrations'
    | '/servers'
    | '/settings'
    | '/storage'
    | '/tasks'
    | '/terminal'
    | '/workspaces'
    | '/api/chat'
    | '/files/$'
    | '/tasks/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/approvals'
    | '/audit-log'
    | '/chat'
    | '/control-plane'
    | '/dashboard'
    | '/databases'
    | '/files'
    | '/integrations'
    | '/servers'
    | '/settings'
    | '/storage'
    | '/tasks'
    | '/terminal'
    | '/workspaces'
    | '/api/chat'
    | '/'
    | '/files/$'
    | '/tasks/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/approvals'
    | '/_authenticated/audit-log'
    | '/_authenticated/chat'
    | '/_authenticated/control-plane'
    | '/_authenticated/dashboard'
    | '/_authenticated/databases'
    | '/_authenticated/files'
    | '/_authenticated/integrations'
    | '/_authenticated/servers'
    | '/_authenticated/settings'
    | '/_authenticated/storage'
    | '/_authenticated/tasks'
    | '/_authenticated/terminal'
    | '/_authenticated/workspaces'
    | '/api/chat'
    | '/_authenticated/'
    | '/_authenticated/files/$'
    | '/_authenticated/tasks/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspaces': {
      id: '/_authenticated/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/terminal': {
      id: '/_authenticated/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof AuthenticatedTerminalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/storage': {
      id: '/_authenticated/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof AuthenticatedStorageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servers': {
      id: '/_authenticated/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof AuthenticatedServersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/files': {
      id: '/_authenticated/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthenticatedFilesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/databases': {
      id: '/_authenticated/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof AuthenticatedDatabasesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/control-plane': {
      id: '/_authenticated/control-plane'
      path: '/control-plane'
      fullPath: '/control-plane'
      preLoaderRoute: typeof AuthenticatedControlPlaneRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/$id': {
      id: '/_authenticated/tasks/$id'
      path: '/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof AuthenticatedTasksIdRouteImport
      parentRoute: typeof AuthenticatedTasksRoute
    }
    '/_authenticated/files/$': {
      id: '/_authenticated/files/$'
      path: '/$'
      fullPath: '/files/$'
      preLoaderRoute: typeof AuthenticatedFilesSplatRouteImport
      parentRoute: typeof AuthenticatedFilesRoute
    }
  }
}

interface AuthenticatedFilesRouteChildren {
  AuthenticatedFilesSplatRoute: typeof AuthenticatedFilesSplatRoute
}

const AuthenticatedFilesRouteChildren: AuthenticatedFilesRouteChildren = {
  AuthenticatedFilesSplatRoute: AuthenticatedFilesSplatRoute,
}

const AuthenticatedFilesRouteWithChildren =
  AuthenticatedFilesRoute._addFileChildren(AuthenticatedFilesRouteChildren)

interface AuthenticatedTasksRouteChildren {
  AuthenticatedTasksIdRoute: typeof AuthenticatedTasksIdRoute
}

const AuthenticatedTasksRouteChildren: AuthenticatedTasksRouteChildren = {
  AuthenticatedTasksIdRoute: AuthenticatedTasksIdRoute,
}

const AuthenticatedTasksRouteWithChildren =
  AuthenticatedTasksRoute._addFileChildren(AuthenticatedTasksRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedControlPlaneRoute: typeof AuthenticatedControlPlaneRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDatabasesRoute: typeof AuthenticatedDatabasesRoute
  AuthenticatedFilesRoute: typeof AuthenticatedFilesRouteWithChildren
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedServersRoute: typeof AuthenticatedServersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStorageRoute: typeof AuthenticatedStorageRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRouteWithChildren
  AuthenticatedTerminalRoute: typeof AuthenticatedTerminalRoute
  AuthenticatedWorkspacesRoute: typeof AuthenticatedWorkspacesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedControlPlaneRoute: AuthenticatedControlPlaneRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDatabasesRoute: AuthenticatedDatabasesRoute,
  AuthenticatedFilesRoute: AuthenticatedFilesRouteWithChildren,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedServersRoute: AuthenticatedServersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStorageRoute: AuthenticatedStorageRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRouteWithChildren,
  AuthenticatedTerminalRoute: AuthenticatedTerminalRoute,
  AuthenticatedWorkspacesRoute: AuthenticatedWorkspacesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
